Align nucleotide hip (#16)
* Set popcnt builtin instruction as default

Remove fallback popcount fallback code

* Unwrap Operation Template for Pop64

* Remove LittleEndian Support

Some swaps are still used. Different sorted output for equivalent readU
functions despite similar code, and does not match golden. Left untouched.

* BUGFIX: Readded endian conversion

* Reduce endian compatibility

endian_swap.h used only for checking host endianness (reference.cpp)

Mistakenlly had support as if big endian was default. This was the
previous error too.

* Remove different Endianness support

Assumes system is little endian

* Comments + Assertions: RM word_io.h old function descriptions

No logic or functional changes. Purely comments and assertions.

* Split searchSeedBi into pt1 and pt2

This has made the step super slow.... but its temporary

* HIP Definitions. Works for compiling. Issues in runtime

Debugging hip kernels. But tested compatibility with hipcc and
amdclang++ targetting original cpu

* OMP,OMPGPU,HIP_KERNELS targettable + constexpr

Via directives. HIP Kernels are not functional, but at least they are
compilable at the moment.

AMD_HOST_DEV macro may be deprecable as all functions targetted by
__device__ were correct when changed to constexpr

* Missed Macros -> constexpr

* Debugging Hip Kernel with 1 Thread

+ Added repcnt to searchAllSeedsDoAll
+ Set seedAlignerSearchState to be allocated on the heap

ERROR: Illegal Memory Accesses

* Revert to OMP

* Combined seedSearchBi back into 1

Interesting ibatch_size can be adjusted slightly before call of the
seedSearchBi function and it will still work for OMP
(tried 64 and 512. 64 worked, 512 failed)

Slight compilation issue vai SS_SIZE for hip kernel

* searchSeedBi HIP Kernel

Change Makefile to enable HIP_KERNELS compilation flag. Disables OMP
acceleration in loop.

* Remove bwops argument instruction from seedsDoAll

* Remove LittleEndian Support

Some swaps are still used. Different sorted output for equivalent readU
functions despite similar code, and does not match golden. Left untouched.

* BUGFIX: Readded endian conversion

* Reduce endian compatibility

endian_swap.h used only for checking host endianness (reference.cpp)

Mistakenlly had support as if big endian was default. This was the
previous error too.

* Remove different Endianness support

Assumes system is little endian

* Comments + Assertions: RM word_io.h old function descriptions

No logic or functional changes. Purely comments and assertions.

* HIP Kernel Dependencies

Changed all dependencies of searchSeedBi into constexpr and verified
correctness.

HIP kernel excluded from commit for runtime issues, but all dependencies
compile to target GPU. HIPCC and AMDCLANG++ can target the hip kernels.
See branch:hip-dev

AMD_HOST_DEV macro may be deprecable as all functions targetted by
__device__ were correct when changed to constexpr

* WIP alignNucleotide

* WIP, hip compiles... but now avx doesn't?

And reading the binary is having problems....

* Changed Makefile CXX flags for default testing

* WIP debug statements

* Fix offset factor by 32x

* WIP Debugging: Print statements for AVX and Threads

Although threads seem to propagate through lazyF, this comes from
loading from pvFStore.

* WIP Print statements... writine race condition?

pvFStore seems to have a value written to the second byte after the
first loop?

* Fix offset pointers in uint8_t

* Partial match

Mismatching for large N

* HIP Port of alignNucleotides

* WIP multiple GPU blocks aligning

* Weird batching works with 1 per task

* Block indexing is having issues

launchin 10k kernels all of 1 block works fine. But multiple blocks
sometimes has errors.

* Switch so npar is number of blocks

WIP, only 1 block launch works

* Parallelized SSERegI Test

* Align Nucleotides in HIP

32 lane (only, hardcoded in certain areas). 8bit scores.

Build with test_align_ee8 target to test only

* Move batchLaunch only into testing (devsupport/)

This means aligner_swsse_ee_u8.cpp only has __device__ annotations,
but to call and organize into blocks for gpu alignment another function
is used.