HIP searchSeedBi (#14)
* Set popcnt builtin instruction as default

Remove fallback popcount fallback code

* Unwrap Operation Template for Pop64

* Remove LittleEndian Support

Some swaps are still used. Different sorted output for equivalent readU
functions despite similar code, and does not match golden. Left untouched.

* BUGFIX: Readded endian conversion

* Reduce endian compatibility

endian_swap.h used only for checking host endianness (reference.cpp)

Mistakenlly had support as if big endian was default. This was the
previous error too.

* Remove different Endianness support

Assumes system is little endian

* Comments + Assertions: RM word_io.h old function descriptions

No logic or functional changes. Purely comments and assertions.

* Split searchSeedBi into pt1 and pt2

This has made the step super slow.... but its temporary

* HIP Definitions. Works for compiling. Issues in runtime

Debugging hip kernels. But tested compatibility with hipcc and
amdclang++ targetting original cpu

* OMP,OMPGPU,HIP_KERNELS targettable + constexpr

Via directives. HIP Kernels are not functional, but at least they are
compilable at the moment.

AMD_HOST_DEV macro may be deprecable as all functions targetted by
__device__ were correct when changed to constexpr

* Missed Macros -> constexpr

* Debugging Hip Kernel with 1 Thread

+ Added repcnt to searchAllSeedsDoAll
+ Set seedAlignerSearchState to be allocated on the heap

ERROR: Illegal Memory Accesses

* Revert to OMP

* Combined seedSearchBi back into 1

Interesting ibatch_size can be adjusted slightly before call of the
seedSearchBi function and it will still work for OMP
(tried 64 and 512. 64 worked, 512 failed)

Slight compilation issue vai SS_SIZE for hip kernel

* searchSeedBi HIP Kernel

Change Makefile to enable HIP_KERNELS compilation flag. Disables OMP
acceleration in loop.

* Remove bwops argument instruction from seedsDoAll

* Remove LittleEndian Support

Some swaps are still used. Different sorted output for equivalent readU
functions despite similar code, and does not match golden. Left untouched.

* BUGFIX: Readded endian conversion

* Reduce endian compatibility

endian_swap.h used only for checking host endianness (reference.cpp)

Mistakenlly had support as if big endian was default. This was the
previous error too.

* Remove different Endianness support

Assumes system is little endian

* Comments + Assertions: RM word_io.h old function descriptions

No logic or functional changes. Purely comments and assertions.

* HIP Kernel Dependencies

Changed all dependencies of searchSeedBi into constexpr and verified
correctness.

HIP kernel excluded from commit for runtime issues, but all dependencies
compile to target GPU. HIPCC and AMDCLANG++ can target the hip kernels.
See branch:hip-dev

AMD_HOST_DEV macro may be deprecable as all functions targetted by
__device__ were correct when changed to constexpr